resolver: nightly-2017-09-03
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.10.0.1
- StateVar-1.1.0.4
- adjunctions-4.3
- base-orphans-0.6
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- brick-0.20.1
- bytes-0.15.3
- call-stack-0.1.0
- cereal-0.5.4.0
- comonad-5.0.2
- contravariant-1.4
- data-clist-0.1.2.0
- distributive-0.5.3
- dlist-0.8.0.3
- exceptions-0.8.3
- fail-4.9.0.0
- fgl-5.5.3.1
- free-4.12.4
- hashable-1.2.6.1
- integer-logarithms-1.0.2
- kan-extensions-5.0.2
- lens-4.15.3
- linear-1.20.7
- megaparsec-6.1.1x
- microlens-0.4.8.0
- microlens-mtl-0.1.11.0
- microlens-th-0.4.1.1
- mtl-2.2.1
- parallel-3.2.1.1
- parsec-3.1.11
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2.1
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- scientific-0.3.5.1
- semigroupoids-5.2.1
- semigroups-0.18.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.2
- text-zipper-0.10
- tf-random-0.5
- th-abstraction-0.2.3.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- utf8-string-1.0.1.1
- vector-0.12.0.1
- void-0.7.2
- vty-5.16
- word-wrap-0.1
- cabal-doctest-1.0.2
- case-insensitive-1.2.0.10
- parser-combinators-0.2.0

